[package]
name = "darkwire-relay"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
darkwire-protocol = { path = "../darkwire-protocol" }
tracing.workspace = true
